version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  # Uncomment for local file logger - File logger does not work in AWS Lambda
  # file:
  #   class: logging.handlers.RotatingFileHandler
  #   level: DEBUG 
  #   formatter: simple
  #   filename: new-relic-thread-profile-trigger.log
  #   maxBytes: 10485760
  #   backupCount: 5
root:
  level: DEBUG
  handlers: [console] #, file]