AWSTemplateFormatVersion: "2010-09-09"
Description: Secrets to be stored in AWS Secrets Manager

Parameters:
  pProduct:
    Description: Name of the instance
    Type: String
  pEnvironment:
    Description: Environment Name
    Type: String
  pAdminRole:
    Description: AWS Role(s) to have admin access
    Type: String
  pDisbursementCode:
    Description: Customer Disbursement Code
    Type: String
  pResourceOwner:
    Type: String
  pAPRMID:
    Description: APRM ID
    Type: String
  pAccountId:
    Type: String
  pDataClassification:
    Type: String
  pLambdaRole:
    Type: String
  pCodePipelineActionRole:
    Type: String
  sNRUsername:
    Type: String
  sNRPassword:
    Type: String
  sNRApiKey:
    Type: String

Resources:
  rLoginSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: NRAutomation/NewRelicFormLogin
      Description: This secret contains credentials for a New Relic Form Login
      SecretString: !Sub '{"username":"${sNRUsername}", "password":"${sNRPassword}"}'
      Tags:
        - Key: DisbursementCode
          Value: !Ref pDisbursementCode
        - Key: ResourceOwner
          Value: !Ref pResourceOwner
        - Key: APRMID
          Value: !Ref pAPRMID
        - Key: ResourceName
          Value: !Ref pProduct
        - Key: Environment
          Value: !Ref pEnvironment
        - Key: DataClassification
          Value: !Ref pDataClassification

  rLoginSecretsPolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref rLoginSecret
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Resource: "*"
            Action: "SecretsManager:GetSecretValue"
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${pAccountId}:role/${pLambdaRole}
          - Resource: "*"
            Action: "SecretsManager:*"
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${pAccountId}:role/${pLambdaRole}
                - !Sub arn:aws:iam::${pAccountId}:role/${pAdminRole}
                - !Sub arn:aws:iam::${pAccountId}:role/${pCodePipelineActionRole}

  rAPIKeySecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: NRAutomation/NewRelicAPIKey
      Description: This secret contains a new relic GraphQL User API Key
      SecretString: !Sub '{"api-key":"${sNRApiKey}"}'
      Tags:
        - Key: DisbursementCode
          Value: !Ref pDisbursementCode
        - Key: ResourceOwner
          Value: !Ref pResourceOwner
        - Key: APRMID
          Value: !Ref pAPRMID
        - Key: ResourceName
          Value: !Ref pProduct
        - Key: Environment
          Value: !Ref pEnvironment
        - Key: DataClassification
          Value: !Ref pDataClassification

  rAPIKeySecretsPolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref rAPIKeySecret
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Resource: "*"
            Action: "SecretsManager:GetSecretValue"
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${pAccountId}:role/${pLambdaRole}
          - Resource: "*"
            Action: "SecretsManager:*"
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${pAccountId}:role/${pLambdaRole}
                - !Sub arn:aws:iam::${pAccountId}:role/${pAdminRole}
                - !Sub arn:aws:iam::${pAccountId}:role/${pCodePipelineActionRole}